# plugin install format is subdir -> source site -> pluginpath
# At this time only civitai is supported
embeddings:
  #Place Textual Inversion embeddings here
  civitai:
    # CharTurner https://civitai.com/models/3036?modelVersionId=3334 charturner
    https://civitai.com/api/download/models/3334
models:
  hypernetworks:
    #Place hypernetworks here
    civitai:
      # [Toru8P] Waven Chibi Style https://civitai.com/models/4379/toru8p-waven-chibi-style 
      https://civitai.com/api/download/models/5255
  Stable-diffusion:
    #Put Stable Diffusion checkpoints here
    civitai:
      # Deliberate https://civitai.com/models/4823/deliberate 
      https://civitai.com/api/download/models/15236
  Lora:
    civitai:
      # Studio Ghibli Style https://civitai.com/models/6526/studio-ghibli-style-lora ghibli style
      https://civitai.com/api/download/models/7657

#todo: support every plugin type on civitai
#todo: support ControlNet installation