# plugin install format is subdir -> source site -> pluginpath
# At this time only civitai is supported
embeddings:
  #Place Textual Inversion embeddings here
  civitai:
    #models/9857 #CharTurner
    https://civitai.com/api/download/models/9857
models:
  hypernetworks:
    #Place hypernetworks here
    civitai:
      https://civitai.com/api/download/models/5255 # [Toru8P] Waven Chibi Style
  Stable-diffusion:
    #Put Stable Diffusion checkpoints here
    civitai:
      https://civitai.com/api/download/models/15236 # Deliberate
  Lora:
    civitai:
      https://civitai.com/api/download/models/7657 # Studio Ghibli Style

#todo: support every plugin type on civitai
#todo: support ControlNet installation