#only used to install models from hugging face for now
#format is usecase -> site -> account/modelname
models:
  huggingface:
    - PygmalionAI/pygmalion-6b
    - Neko-Institute-of-Science/pygmalion-7b